extends: ['@r1oga']
overrides:
  - files: ['src/**/index.ts']
    rules:
      'import/no-default-export': off
      'import/prefer-default-export': off
      sort-exports: off
  - files: ['src/**/*.ts']
    rules:
      no-useless-constructor: off
  - files: ['scripts/*.ts']
    rules:
      no-console: off
      '@typescript-eslint/restrict-template-expressions': off
      '@typescript-eslint/ban-ts-comment': off
  - files: ['test/integration/*.ts']
    rules:
      'jest/expect-expect': off
      '@typescript-eslint/ban-ts-comment': off
  - files: ['src/handlers/validate.ts']
    rules:
      '@typescript-eslint/strict-boolean-expressions': off
  - files: ['test/setup.e2e.ts']
    rules:
      '@typescript-eslint/no-unused-vars': off
  - files: ['test/e2e/whitelist-routes.test.ts', 'src/controllers/**/*.ts']
    rules:
      '@typescript-eslint/no-misused-promises': off
